### ISSUE TITLE
uncaught exception: request.headers.split is not a function

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.iot#1093]
**Describe the bug**  
After updating iot Adapter to 5.0.8 errors are shown in log

**Versions:**  
 - Adapter version: 5.0.8
 - JS-Controller version: 7.0.7
 - Node version:  v24.11.1

**Screenshots & Logfiles**  
```
2025-12-12 22:47:18.455 - info: host.ioBroker iobroker host.ioBroker Adapter "system.adapter.iot.0" is started
2025-12-12 22:47:18.457 - info: host.ioBroker "system.adapter.iot.0" enabled
2025-12-12 22:47:18.668 - info: host.ioBroker instance system.adapter.iot.0 in version "5.0.8" started with pid 25067
2025-12-12 22:47:19.195 - info: iot.0 (25067) starting. Version 5.0.8 in /opt/iobroker/node_modules/iobroker.iot, node: v24.11.1, js-controller: 7.0.7
2025-12-12 22:47:19.260 - info: iot.0 (25067) Connecting with a18wym7vjdl22g.iot.eu-west-1.amazonaws.com
2025-12-12 22:47:19.287 - error: iot.0 (25067) uncaught exception: request.headers.split is not a function
2025-12-12 22:47:19.287 - error: iot.0 (25067) TypeError: request.headers.split is not a function
at setHeadersOnRequest (/opt/iobroker/node_modules/@sentry/src/integrations/undici/index.ts:275:1)
at _onRequestCreate (/opt/iobroker/node_modules/@sentry/src/integrations/undici/index.ts:185:1)
at Channel.publish (node:diagnostics_channel:156:9)
at new Request (node:internal/deps/undici/undici:2661:27)
at Client.[dispatch] (node:internal/deps/undici/undici:8499:25)
at Client.dispatch (node:internal/deps/undici/undici:1993:33)
at Pool.[dispatch] (node:internal/deps/undici/undici:2258:32)
at Pool.dispatch (node:internal/deps/undici/undici:1993:33)
at Agent.[dispatch] (node:internal/deps/undici/undici:8963:27)
at Agent.dispatch (node:internal/deps/undici/undici:1993:33)
2025-12-12 22:47:19.288 - error: iot.0 (25067) request.headers.split is not a function
2025-12-12 22:47:19.291 - info: iot.0 (25067) terminating
2025-12-12 22:47:19.292 - warn: iot.0 (25067) Terminated (UNCAUGHT_EXCEPTION): Without reason
2025-12-12 22:47:19.343 - error: host.ioBroker Caught by controller[1]: TypeError: request.headers.split is not a function
2025-12-12 22:47:19.343 - error: host.ioBroker Caught by controller[1]: at setHeadersOnRequest (/opt/iobroker/node_modules/@sentry/src/integrations/undici/index.ts:275:1)
2025-12-12 22:47:19.343 - error: host.ioBroker Caught by controller[1]: at _onRequestCreate (/opt/iobroker/node_modules/@sentry/src/integrations/undici/index.ts:185:1)
2025-12-12 22:47:19.344 - error: host.ioBroker Caught by controller[1]: at Channel.publish (node:diagnostics_channel:156:9)
2025-12-12 22:47:19.344 - error: host.ioBroker Caught by controller[1]: at new Request (node:internal/deps/undici/undici:2661:27)
2025-12-12 22:47:19.344 - error: host.ioBroker Caught by controller[1]: at Client.[dispatch] (node:internal/deps/undici/undici:8499:25)
2025-12-12 22:47:19.344 - error: host.ioBroker Caught by controller[1]: at Client.dispatch (node:internal/deps/undici/undici:1993:33)
2025-12-12 22:47:19.344 - error: host.ioBroker Caught by controller[1]: at Pool.[dispatch] (node:internal/deps/undici/undici:2258:32)
2025-12-12 22:47:19.344 - error: host.ioBroker Caught by controller[1]: at Pool.dispatch (node:internal/deps/undici/undici:1993:33)
2025-12-12 22:47:19.345 - error: host.ioBroker Caught by controller[1]: at Agent.[dispatch] (node:internal/deps/undici/undici:8963:27)
2025-12-12 22:47:19.345 - error: host.ioBroker Caught by controller[1]: at Agent.dispatch (node:internal/deps/undici/undici:1993:33)
2025-12-12 22:47:19.345 - error: host.ioBroker instance system.adapter.iot.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
2025-12-12 22:47:19.345 - info: host.ioBroker Restart adapter system.adapter.iot.0 because enabled
2025-12-12 22:47:19.559 - info: host.ioBroker iobroker exit 0
```

**Comment by GermanBluefox** [comment]
Here is the similar error: https://github.com/Grizzelbee/ioBroker.mielecloudservice/issues/507

**Comment by mcm1957** [comment]
BETA === LATEST
Only two names for the same repo
