### ISSUE TITLE
Adapter crashes immediately

### ISSUE THREAD

**Issue by PlanLos23** [ioBroker/ioBroker.iot#1158]
**Describe the bug**  
After updating to version 5.0.12, the adapter crashes immediately.

**To Reproduce**  
1. activate the adapter
2. crash - see error

**Expected behavior**  
that it runs as before

**Screenshots & Logfiles**  
host.ioBroker | 2026-05-06 08:14:03.246 | error | instance system.adapter.iot.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.ioBroker | 2026-05-06 08:14:03.246 | error | Caught by controller[0]: at Pool.[Intercepted Dispatch] (node:internal/deps/undici/undici:681:33)
host.ioBroker | 2026-05-06 08:14:03.246 | error | Caught by controller[0]: at Pool.[dispatch] (node:internal/deps/undici/undici:935:32)
host.ioBroker | 2026-05-06 08:14:03.246 | error | Caught by controller[0]: at Client.dispatch (node:internal/deps/undici/undici:704:44)
host.ioBroker | 2026-05-06 08:14:03.246 | error | Caught by controller[0]: at Client.[Intercepted Dispatch] (node:internal/deps/undici/undici:688:16)
host.ioBroker | 2026-05-06 08:14:03.245 | error | Caught by controller[0]: at Intercept (node:internal/deps/undici/undici:7649:20)
host.ioBroker | 2026-05-06 08:14:03.245 | error | Caught by controller[0]: at Client.[dispatch] (node:internal/deps/undici/undici:7916:25)
host.ioBroker | 2026-05-06 08:14:03.245 | error | Caught by controller[0]: at new Request (node:internal/deps/undici/undici:2124:27)
host.ioBroker | 2026-05-06 08:14:03.245 | error | Caught by controller[0]: at Channel.publish (node:diagnostics_channel:156:9)
host.ioBroker | 2026-05-06 08:14:03.245 | error | Caught by controller[0]: at _onRequestCreate (/opt/iobroker/node_modules/@sentry/src/integrations/undici/index.ts:200:7)
host.ioBroker | 2026-05-06 08:14:03.245 | error | Caught by controller[0]: at setHeadersOnRequest (/opt/iobroker/node_modules/@sentry/src/integrations/undici/index.ts:289:39)
host.ioBroker | 2026-05-06 08:14:03.245 | error | Caught by controller[0]: TypeError: request.headers.split is not a function
iot.0 | 2026-05-06 08:14:03.155 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
iot.0 | 2026-05-06 08:14:03.155 | info | terminating
iot.0 | 2026-05-06 08:14:03.148 | error | request.headers.split is not a function
iot.0 | 2026-05-06 08:14:03.148 | error | TypeError: request.headers.split is not a function at setHeadersOnRequest (/opt/iobroker/node_modules/@sentry/src/integrations/undici/index.ts:289:39) at _onRequestCreate (/opt/iobroker/node_modules/@sentry/src/integrations/undici/index.ts:200:7) at Channel.publish (node:diagnostics_channel:156:9) at new Request (node:internal/deps/undici/undici:2124:27) at Client.[dispatch] (node:internal/deps/undici/undici:7916:25) at Intercept (node:internal/deps/undici/undici:7649:20) at Client.[Intercepted Dispatch] (node:internal/deps/undici/undici:688:16) at Client.dispatch (node:internal/deps/undici/undici:704:44) at Pool.[dispatch] (node:internal/deps/undici/undici:935:32) at Pool.[Intercepted Dispatch] (node:internal/deps/undici/undici:681:33)
iot.0 | 2026-05-06 08:14:03.147 | error | uncaught exception: request.headers.split is not a function
iot.0 | 2026-05-06 08:14:03.072 | info | Connecting with a18wym7vjdl22g.iot.eu-west-1.amazonaws.com
iot.0 | 2026-05-06 08:14:02.993 | info | starting. Version 5.0.12 in /opt/iobroker/node_modules/iobroker.iot, node: v22.22.0, js-controller: 7.0.7

**Versions:**  
 - Adapter version: 5.0.12
 - JS-Controller version: 7.0.7
 - Node version: 22.22.0
 - Operating system: Docker on Ubuntu

**Additional context**  
The issue started after updating from 5.0.7 to 5.0.12.

**Comment by mcm1957** [comment]
updating to js-controller 7.1.x (still beta) or disabling sentry for this adapter should fix the problem. Please give it a try.

**Comment by PlanLos23** [comment]
Hey there, thanks for help. Sentry alone wasn't the solution. Updating to 7.1 fixed it.
