### ISSUE TITLE
upgrade to v2.0.11 breaks ioBoker ( Error: Cannot find module 'tar'Require stack:- )

### ISSUE THREAD

**Issue by loki-sft** [ioBroker/ioBroker.iot#677]
Upgrading ANY other module after upgrading IOT module to V2.011 produces this error:
`node:internal/modules/cjs/loader:1080 throw err; ^Error: Cannot find module 'tar'Require stack:- /opt/iobroker/node_modules/@iobroker/js-controller-cli/build/lib/setup/setupBackup.js- /opt/iobroker/node_modules/@iobroker/js-controller-cli/build/index.js- /opt/iobroker/node_modules/iobroker.js-controller/iobroker.js at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15) at Module._load (node:internal/modules/cjs/loader:922:27) at Module.require (node:internal/modules/cjs/loader:1143:19) at require (node:internal/modules/cjs/helpers:121:18) at Object.<anonymous> (/opt/iobroker/node_modules/@iobroker/js-controller-cli/build/lib/setup/setupBackup.js:12:31) at Module._compile (node:internal/modules/cjs/loader:1256:14) at Module._extensions..js (node:internal/modules/cjs/loader:1310:10) at Module.load (node:internal/modules/cjs/loader:1119:32) at Module._load (node:internal/modules/cjs/loader:960:12) at Module.require (node:internal/modules/cjs/loader:1143:19) { code: 'MODULE_NOT_FOUND', requireStack: [ '/opt/iobroker/node_modules/@iobroker/js-controller-cli/build/lib/setup/setupBackup.js', '/opt/iobroker/node_modules/@iobroker/js-controller-cli/build/index.js', '/opt/iobroker/node_modules/iobroker.js-controller/iobroker.js' ]}Node.js v18.17.1

ERROR: Process exited with code 1`

**Comment by Apollon77** [comment]
I nmore think that there is something strange in your local installation ... because tar is installed by js.controller ... you can try in /opt/iobroker/node_modules if you find a directory "tar" ... if not thats more a forum issueto fix your system

**Comment by loki-sft** [comment]
Before the upgrade there are 3 tar forlder, "tar", "tar-fs" and "tar-stream", after the upgrade all tar-folders are gone.

**Comment by Apollon77** [comment]
Then this is a strange npm issue and can have to do with a broken package-lock File or such ...
